name: nfc_kasse_admin
description: Verwaltungstool für NFC-Kasse — Konfiguration, Bon-Layout, Dienst-Steuerung.
publisher: "Kim Schehl"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  yaml: ^3.1.2
  win32_registry: ^1.1.4
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
