; NFC-Kasse Backend installer.
; Build with (from repo root, after PyInstaller + WinSW staging are done):
;   "%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe" packaging\innosetup\nfc_kasse_installer.iss
;
; Expects, relative to this file:
;   ..\pyinstaller\dist\NfcKasseBackend\   (PyInstaller onedir output)
;   ..\winsw\NfcKasseService.exe           (downloaded, see packaging\build_installer.bat)
;   ..\winsw\NfcKasseService.xml

#define MyAppName "NFC-Kasse Backend"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Kim Schehl"

[Setup]
; Fixed, never change once released -- this is how Inno Setup recognizes
; "this is an upgrade of the same app" across versions.
AppId={{2EF18757-6135-4143-991F-DA4D728CEE16}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\NFC-Kasse
DefaultGroupName=NFC-Kasse
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
OutputBaseFilename=NFC-Kasse-Setup
OutputDir=..\..\packaging\innosetup\dist
SetupIconFile=assets\nfc_kasse.ico
UninstallDisplayIcon={app}\NfcKasseBackend.exe
; Auto-creates a log in %TEMP% ("Setup Log <date>.txt") on every run, no
; /LOG flag needed -- otherwise a normal double-click install leaves no
; record at all if something goes wrong, which is exactly the failure mode
; a real customer would hit (they don't know to pass command-line flags).
SetupLogging=yes
Compression=lzma2
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "Desktop-Symbol erstellen"; GroupDescription: "Zusätzliche Symbole:"

[Dirs]
; The single load-bearing piece keeping an uninstall from ever touching real
; kasse.db/config.env/logs/backups: this directory (and only this one) is
; flagged uninsneveruninstall. Program files in {app} do NOT get this flag
; -- those are meant to disappear on uninstall.
Name: "{commonappdata}\NFC-Kasse"; Flags: uninsneveruninstall

[Files]
Source: "..\pyinstaller\dist\NfcKasseBackend\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "..\winsw\NfcKasseService.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\winsw\NfcKasseService.xml"; DestDir: "{app}"; Flags: ignoreversion
; Nothing here ever targets {commonappdata} -- an upgrade install therefore
; never touches real data, purely by construction, no special-case logic
; needed.

[Icons]
Name: "{group}\NFC-Kasse öffnen"; Filename: "http://localhost:8000/webapp"
Name: "{group}\Dienst starten"; Filename: "{app}\NfcKasseService.exe"; Parameters: "start"
Name: "{group}\Dienst stoppen"; Filename: "{app}\NfcKasseService.exe"; Parameters: "stop"
Name: "{commondesktop}\NFC-Kasse öffnen"; Filename: "http://localhost:8000/webapp"; Tasks: desktopicon
; "NFC-Kasse Backend deinstallieren" is auto-generated by Inno Setup.

[Run]
Filename: "{app}\NfcKasseService.exe"; Parameters: "install"; Flags: runhidden waituntilterminated; StatusMsg: "Windows-Dienst wird registriert..."
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""NFC-Kasse Backend"" dir=in action=allow program=""{app}\NfcKasseBackend.exe"" enable=yes profile=any"; Flags: runhidden waituntilterminated; StatusMsg: "Firewall-Regel wird eingerichtet..."
; Scoped by program path, not localport -- PORT is user-editable in
; config.env after install, so a port-scoped rule would go stale the moment
; someone changes it. Program-scoped stays correct regardless.
Filename: "{app}\NfcKasseService.exe"; Parameters: "start"; Flags: runhidden waituntilterminated; StatusMsg: "Dienst wird gestartet..."
Filename: "http://localhost:8000/webapp"; Flags: postinstall shellexec skipifsilent nowait; Description: "NFC-Kasse jetzt öffnen"
; Assumes fresh-install defaults (HOST/PORT/WEBAPP_ROUTE as generated by
; service_main.py's config.env template) -- correct for a first install,
; goes stale if PORT/WEBAPP_ROUTE are edited later. Same caveat applies to
; the Start Menu/Desktop shortcuts above.

[UninstallRun]
; Inno Setup guarantees these run BEFORE [Files]-installed files are
; deleted -- required ordering, since a service can't be cleanly unregistered
; once the exe backing it no longer exists.
Filename: "{app}\NfcKasseService.exe"; Parameters: "stop"; Flags: runhidden waituntilterminated; RunOnceId: "StopService"
Filename: "{app}\NfcKasseService.exe"; Parameters: "uninstall"; Flags: runhidden waituntilterminated; RunOnceId: "UninstallService"
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""NFC-Kasse Backend"""; Flags: runhidden waituntilterminated; RunOnceId: "RemoveFirewallRule"

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then
  begin
    // Upgrade-in-place safety: a matching AppId does NOT automatically stop
    // a running service before [Files] overwrites it. Without this, an
    // update over a live install fails outright with a file-in-use error
    // the moment [Files] tries to replace NfcKasseBackend.exe while the
    // service still holds it open. Both calls are unconditional and
    // harmless on a fresh install, where the service isn't registered yet
    // (non-zero exit, ignored).
    Exec(ExpandConstant('{app}\NfcKasseService.exe'), 'stop', '',
      SW_HIDE, ewWaitUntilTerminated, ResultCode);
    // Also uninstall the old registration, not just stop it -- otherwise
    // [Run]'s later 'install' step fails with "service already exists"
    // every single upgrade (harmless -- the following 'start' step still
    // succeeds -- but it logs a scary-looking FATAL line in wrapper.log
    // for something that isn't actually a problem). Re-registering fresh
    // each time also means an updated WinSW XML (e.g. changed recovery
    // settings in a future release) actually takes effect on upgrade,
    // rather than the SCM keeping stale settings from the previous
    // version's registration.
    Exec(ExpandConstant('{app}\NfcKasseService.exe'), 'uninstall', '',
      SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;
