; NFC-Kasse Backend installer.
; Build with (from repo root, after PyInstaller + WinSW staging are done):
;   "%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe" packaging\innosetup\nfc_kasse_installer.iss
;
; Expects, relative to this file:
;   ..\pyinstaller\dist\NfcKasseBackend\   (PyInstaller onedir output)
;   ..\winsw\NfcKasseService.exe           (downloaded, see packaging\build_installer.bat)
;   ..\winsw\NfcKasseService.xml

#define MyAppName "NFC-Kasse Backend"
; Overridden from build_installer.bat via "ISCC /DMyAppVersion=X.Y.Z ..." --
; that value comes straight from nfc_kasse_app\pubspec.yaml, the same single
; source of truth build_and_deploy.bat already names the APK after. This
; fallback only matters for a manual/local ISCC run without that flag.
#ifndef MyAppVersion
  #define MyAppVersion "1.0.0"
#endif
#define MyAppPublisher "Kim Schehl"
; Real single braces here (not the {{ escape [Setup] directives need for a
; literal leading brace) -- ISPP substitutes {#MyAppId} as plain text before
; Inno's own constant-escaping pass ever runs, so AppId={{#MyAppId} below
; comes out exactly as "AppId={{2EF18757-...}", the form Inno requires. The
; single-brace form is also what [Code] needs for the uninstall registry key.
#define MyAppId "{2EF18757-6135-4143-991F-DA4D728CEE16}"

[Setup]
; Fixed, never change once released -- this is how Inno Setup recognizes
; "this is an upgrade of the same app" across versions.
AppId={{#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\NFC-Kasse
DefaultGroupName=NFC-Kasse
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
OutputBaseFilename=NFC-Kasse-Setup
OutputDir=..\..\packaging\innosetup\dist
SetupIconFile=assets\nfc_kasse.ico
UninstallDisplayIcon={app}\NfcKasseBackend.exe
; Auto-creates a log in %TEMP% ("Setup Log <date>.txt") on every run, no
; /LOG flag needed -- otherwise a normal double-click install leaves no
; record at all if something goes wrong, which is exactly the failure mode
; a real customer would hit (they don't know to pass command-line flags).
SetupLogging=yes
Compression=lzma2
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "Desktop-Symbol erstellen"; GroupDescription: "Zusätzliche Symbole:"

[Dirs]
; Keeps kasse.db/config.env/bon.yaml/logs/backups untouched by Inno's own
; uninstall-file-removal logic and by every UPGRADE install (Inno never
; removes an uninsneveruninstall dir just because a newer version is being
; installed over it). Program files in {app} do NOT get this flag -- those
; are meant to disappear on uninstall. A real, standalone REMOVAL can still
; delete this directory -- see [UninstallDelete]/InitializeUninstall below,
; which ask the user first (opt-in, defaults to keeping the data).
Name: "{commonappdata}\NFC-Kasse"; Flags: uninsneveruninstall

[Files]
Source: "..\pyinstaller\dist\NfcKasseBackend\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "..\winsw\NfcKasseService.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\winsw\NfcKasseService.xml"; DestDir: "{app}"; Flags: ignoreversion
; Nothing here ever targets {commonappdata} -- an upgrade install therefore
; never touches real data, purely by construction, no special-case logic
; needed.

[Icons]
Name: "{group}\NFC-Kasse öffnen"; Filename: "http://localhost:8000/webapp"
Name: "{group}\Dienst starten"; Filename: "{app}\NfcKasseService.exe"; Parameters: "start"
Name: "{group}\Dienst stoppen"; Filename: "{app}\NfcKasseService.exe"; Parameters: "stop"
Name: "{commondesktop}\NFC-Kasse öffnen"; Filename: "http://localhost:8000/webapp"; Tasks: desktopicon
; "NFC-Kasse Backend deinstallieren" is auto-generated by Inno Setup.

[Run]
Filename: "{app}\NfcKasseService.exe"; Parameters: "install"; Flags: runhidden waituntilterminated; StatusMsg: "Windows-Dienst wird registriert..."
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""NFC-Kasse Backend"" dir=in action=allow program=""{app}\NfcKasseBackend.exe"" enable=yes profile=any"; Flags: runhidden waituntilterminated; StatusMsg: "Firewall-Regel wird eingerichtet..."
; Scoped by program path, not localport -- PORT is user-editable in
; config.env after install, so a port-scoped rule would go stale the moment
; someone changes it. Program-scoped stays correct regardless.
Filename: "{app}\NfcKasseService.exe"; Parameters: "start"; Flags: runhidden waituntilterminated; StatusMsg: "Dienst wird gestartet..."
Filename: "http://localhost:8000/webapp"; Flags: postinstall shellexec skipifsilent nowait; Description: "NFC-Kasse jetzt öffnen"
; Assumes fresh-install defaults (HOST/PORT/WEBAPP_ROUTE as generated by
; service_main.py's config.env template) -- correct for a first install,
; goes stale if PORT/WEBAPP_ROUTE are edited later. Same caveat applies to
; the Start Menu/Desktop shortcuts above.

[UninstallRun]
; Inno Setup guarantees these run BEFORE [Files]-installed files are
; deleted -- required ordering, since a service can't be cleanly unregistered
; once the exe backing it no longer exists.
Filename: "{app}\NfcKasseService.exe"; Parameters: "stop"; Flags: runhidden waituntilterminated; RunOnceId: "StopService"
Filename: "{app}\NfcKasseService.exe"; Parameters: "uninstall"; Flags: runhidden waituntilterminated; RunOnceId: "UninstallService"
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""NFC-Kasse Backend"""; Flags: runhidden waituntilterminated; RunOnceId: "RemoveFirewallRule"

[UninstallDelete]
; Opt-in only -- ShouldDeleteDataDir() (see [Code]) returns true only if the
; user explicitly confirmed the data-loss warning in InitializeUninstall.
; Left unconfirmed (the default), this entry is skipped entirely and
; C:\ProgramData\NFC-Kasse\ -- config.env, kasse.db, bon.yaml, backups, logs
; -- survives the uninstall untouched, same as today.
Type: filesandordirs; Name: "{commonappdata}\NFC-Kasse"; Check: ShouldDeleteDataDir

[Code]
var
  ModePage: TWizardPage;
  InstallRadio, UpdateRadio, UninstallRadio: TNewRadioButton;

function UninstallRegKey: String;
begin
  Result := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppId}_is1';
end;

function IsAlreadyInstalled: Boolean;
begin
  Result := RegKeyExists(HKLM, UninstallRegKey);
end;

// A plain re-run of Setup (e.g. double-clicking the download again to
// update) would otherwise walk straight into the normal wizard with no
// indication of whether this is a fresh install or an upgrade, and no way
// to uninstall short of hunting it down in "Apps & Features". This page
// makes that explicit and steers "Deinstallieren" to the existing
// uninstaller instead of duplicating its logic here.
procedure InitializeWizard;
var
  installed: Boolean;
begin
  installed := IsAlreadyInstalled;

  ModePage := CreateCustomPage(wpWelcome, 'Installationsmodus',
    'Was möchten Sie tun?');

  InstallRadio := TNewRadioButton.Create(ModePage);
  InstallRadio.Parent := ModePage.Surface;
  InstallRadio.Caption := 'Installieren';
  InstallRadio.Top := 0;
  InstallRadio.Width := ModePage.SurfaceWidth;
  InstallRadio.Enabled := not installed;
  InstallRadio.Checked := not installed;

  UpdateRadio := TNewRadioButton.Create(ModePage);
  UpdateRadio.Parent := ModePage.Surface;
  UpdateRadio.Caption := 'Aktualisieren';
  UpdateRadio.Top := InstallRadio.Top + InstallRadio.Height + 12;
  UpdateRadio.Width := ModePage.SurfaceWidth;
  UpdateRadio.Enabled := installed;
  UpdateRadio.Checked := installed;

  UninstallRadio := TNewRadioButton.Create(ModePage);
  UninstallRadio.Parent := ModePage.Surface;
  UninstallRadio.Caption := 'Deinstallieren';
  UninstallRadio.Top := UpdateRadio.Top + UpdateRadio.Height + 12;
  UninstallRadio.Width := ModePage.SurfaceWidth;
  UninstallRadio.Enabled := installed;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  uninstallString: String;
  resultCode: Integer;
begin
  Result := True;
  if (CurPageID <> ModePage.ID) or not UninstallRadio.Checked then
    exit;

  if RegQueryStringValue(HKLM, UninstallRegKey, 'UninstallString', uninstallString) then
    Exec(RemoveQuotes(uninstallString), '', '', SW_SHOW, ewWaitUntilTerminated, resultCode)
  else
    MsgBox('Bestehende Installation konnte nicht gefunden werden.', mbError, MB_OK);

  // Whatever happened above (uninstalled, or the uninstaller's own confirm
  // prompt was cancelled), this Setup run is done -- continuing on to
  // Select Destination/Ready/Install would just reinstall right over
  // whatever was or wasn't just removed. Abort is Inno Setup's own
  // documented "terminate Setup now" call (not the WinAPI/Delphi one).
  Abort;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then
  begin
    // Upgrade-in-place safety: a matching AppId does NOT automatically stop
    // a running service before [Files] overwrites it. Without this, an
    // update over a live install fails outright with a file-in-use error
    // the moment [Files] tries to replace NfcKasseBackend.exe while the
    // service still holds it open. Both calls are unconditional and
    // harmless on a fresh install, where the service isn't registered yet
    // (non-zero exit, ignored).
    Exec(ExpandConstant('{app}\NfcKasseService.exe'), 'stop', '',
      SW_HIDE, ewWaitUntilTerminated, ResultCode);
    // Also uninstall the old registration, not just stop it -- otherwise
    // [Run]'s later 'install' step fails with "service already exists"
    // every single upgrade (harmless -- the following 'start' step still
    // succeeds -- but it logs a scary-looking FATAL line in wrapper.log
    // for something that isn't actually a problem). Re-registering fresh
    // each time also means an updated WinSW XML (e.g. changed recovery
    // settings in a future release) actually takes effect on upgrade,
    // rather than the SCM keeping stale settings from the previous
    // version's registration.
    Exec(ExpandConstant('{app}\NfcKasseService.exe'), 'uninstall', '',
      SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

// ---------------------------------------------------------------------------
// Uninstaller: optional removal of C:\ProgramData\NFC-Kasse\
// ---------------------------------------------------------------------------

var
  DeleteDataDirConfirmed: Boolean;

// InitializeUninstall runs before Inno's own "really remove NFC-Kasse
// Backend?" confirmation, which is exactly what we want -- asking about
// data loss up front, with "Nein" as the safe default (MB_DEFBUTTON2), so
// hitting Enter without reading never destroys anything.
function InitializeUninstall(): Boolean;
var
  DataDir, NL, Msg: String;
begin
  Result := True;
  DataDir := ExpandConstant('{commonappdata}\NFC-Kasse');
  DeleteDataDirConfirmed := False;
  if DirExists(DataDir) then
  begin
    // Built via a local NL variable rather than inline #13#10 -- ISPP (the
    // preprocessor, a separate pass over the raw text before Pascal Script
    // ever sees it) treats a leading '#' on any line as a directive marker,
    // so a continuation line starting with "#13#10 + ..." fails to compile
    // with "Unknown preprocessor directive". This sidesteps it entirely.
    NL := #13#10;
    Msg := 'Sollen auch alle gespeicherten Daten gelöscht werden?' + NL + NL +
      'ACHTUNG: Dies löscht unwiderruflich die Konfiguration (config.env), ' +
      'die Datenbank (kasse.db) mit allen Kunden, Guthaben und Buchungen, ' +
      'alle Backups, das Bon-Layout (bon.yaml) und alle Protokolle unter:' +
      NL + DataDir + NL + NL +
      'Bei einer späteren Neuinstallation stehen diese Daten dann NICHT ' +
      'mehr zur Verfügung. Wählen Sie "Nein", um sie zu behalten.';
    DeleteDataDirConfirmed := (MsgBox(Msg, mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES);
  end;
end;

// Referenced by [UninstallDelete]'s Check: parameter above.
function ShouldDeleteDataDir(): Boolean;
begin
  Result := DeleteDataDirConfirmed;
end;
