name: nfc_kasse_app
description: NFC-based cashless POS system for events.
publisher: "Kim Schehl"
publish_to: 'none'
# Major, Minor, Patch
version: 1.0.44+46

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  shared_preferences: ^2.3.0
  nfc_manager: ^3.3.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.0
  open_file: ^3.3.2
  qr_flutter: ^4.1.0
  web_socket_channel: ^3.0.1
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/05-single-logo-yellow.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/images/05-single-logo-yellow.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
