"""
License key verification for paid add-on features (PAGER, LEADERBOARD, ...).

A license key is a compact, offline-verifiable token:

    base64url(payload_json) + "." + base64url(signature)

where payload_json is `{"v": 1, "installation_id": "<uuid>", "feature": "<name>"}`
(compact, no padding on either base64url segment) and signature is an
Ed25519 signature over the raw payload_json bytes.

This module only ever needs the PUBLIC key (below) to verify — that's why
it's safe to ship with every install. The matching PRIVATE key never leaves
the developer's own machine; see license_tool/ at the repo root, which is
NOT part of this package and must never be bundled into a build.

One key is scoped to exactly one feature on exactly one installation.
config.py combines this with the existing PAGER=true/LEADERBOARD=true
config.env flags — the flag says "the operator wants this on", a valid
license key says "they're allowed to turn it on"; a feature only actually
activates when both agree.
"""

import base64
import json
import logging

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

logger = logging.getLogger(__name__)

# Public half of the keypair generated by license_tool/generate_keypair.py.
# Safe to be public — only the matching private key (held only by the
# developer) can produce a signature this verifies.
PUBLIC_KEY_B64 = "AVj_42Dpt6cJ-sAhG-jBxWRdYlTZh9sKo_reN39281A"


def _b64_decode(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def _load_public_key() -> Ed25519PublicKey:
    # Re-reads the module attribute on every call (rather than caching at
    # import time) so tests can swap in a test keypair by assigning
    # licensing.PUBLIC_KEY_B64 directly, no monkeypatch fixture needed.
    return Ed25519PublicKey.from_public_bytes(_b64_decode(PUBLIC_KEY_B64))


def verify_feature(feature: str, installation_id: str, license_key: str) -> bool:
    """
    True if license_key is a validly-signed grant of `feature` for exactly
    this installation_id. Every failure mode (missing key, malformed key,
    wrong feature, wrong installation, bad signature) just returns False —
    callers treat that identically to "no license present"; nothing here
    ever raises.
    """
    if not license_key or not installation_id:
        return False
    try:
        payload_b64, sig_b64 = license_key.split(".", 1)
        payload_bytes = _b64_decode(payload_b64)
        signature = _b64_decode(sig_b64)
        _load_public_key().verify(signature, payload_bytes)
        payload = json.loads(payload_bytes)
        if payload.get("feature") == feature and payload.get("installation_id") == installation_id:
            return True
        logger.warning(
            "License key for '%s' has a valid signature but wrong feature/installation_id", feature
        )
        return False
    except InvalidSignature:
        logger.warning("License key for '%s' failed signature verification", feature)
        return False
    except (ValueError, KeyError, TypeError, UnicodeDecodeError) as e:
        logger.warning("License key for '%s' is malformed: %s", feature, e)
        return False
